spring.application.name=bookservice

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/bookservice
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8900/eureka
