spring.application.name=gatewayService

server.port=8080

# routes
spring.cloud.gateway.server.webmvc.routes[0].id=book
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/books,/api/v1/books/**
#spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Path=/api/v1/books/**

# routes orders
spring.cloud.gateway.server.webmvc.routes[1].id=order
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/orders,/api/v1/orders/**
#spring.cloud.gateway.server.webmvc.routes[1].predicates[1]=Path=/api/v1/orders/**

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8900/eureka